### ISSUE TITLE
Raise exception instead of sys.exit()ing on corrupt index file?

### ISSUE THREAD

**Issue by aripollak** [maxmahlke/rocks#27]
I'm currently calling `Rock()` many times from other Python code, but first calling `rocks.set_log_level("critical")` to avoid lots of "Could not identify ..." errors being printed to the console. However, this also seems to hide a critical warning that causes the entire program to exit silently:
https://github.com/maxmahlke/rocks/blob/b44a31d2ee5cab79d3492493b12acbfb37f4b458/rocks/index.py#L388-L397

Would it be possible to change that `sys.exit()` to raise an exception instead, or at least change the `logger.error` calls to `logger.critical` and add a nonzero argument to `sys.exit()`?

Thanks!

**Comment by aripollak** [comment]
For reference, this failed with asteroid number 628250, and happened with a freshly built rocks index.

**Comment by maxmahlke** [comment]
Thanks for reporting this, `rocks` should definitely not exit the program if the name resolution fails. I changed the code to match the default behaviour: if the name resolution fails, `rocks.id` logs a warning and returns a `(None, np.nan)` tuple. This is fixed in version `1.8.11`.

I'm not raising exceptions in these cases as this use case (resolving many identifiers, of which some are invalid) is quite frequent and the user might simply not care about the unidentified ones or prefer to sort them out on their own. I'm open to creating a `NameResolutionFailedWarning` which the user could catch explicitly though, if that is something you'd be interested in.

**Comment by aripollak** [comment]
Thanks! I'm okay with the current behavior without an exception in case of a missing id. 

I did just notice another place where sys.exit() is being called from library code though, which seems like it could be a good candidate for an exception instead: https://github.com/maxmahlke/rocks/blob/9baf317bd0dba317ad0738ca841a1c3efdd19f7b/rocks/index.py#L421-L427

**Comment by maxmahlke** [comment]
Well spotted, it's removed, no more `sys.exit()` outside the `cli` module.
